@echo off
set DATABASE_USER=
set DATABASE_PASSWORD=
set DATABASE_HOST=
set DATABASE_PORT=
set DATABASE_NAME=
set DATABASE_PROVIDER=
set UPDATE_DATABASE=

set SERVER_PORT=
set DEFAULT_PASSWORD=
set LOGGER_LEVEL=
set JWT_SECRET=
set SESSION_TIMEOUT=